apiVersion: v1
kind: ServiceAccount
metadata:
  name: lb-controller-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-controller-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lb-controller-binding
subjects:
  - kind: ServiceAccount
    name: lb-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: lb-controller-role
  apiGroup: rbac.authorization.k8s.io
